# Generated by Django 4.1.5 on 2023-02-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="ISBN",
            new_name="isbn",
        ),
    ]
