# Generated by Django 4.1.5 on 2023-02-19 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_isbn_book_isbn"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="loan",
            name="borrower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.customer"
            ),
        ),
    ]
